### ISSUE TITLE
更新了 many-user 分支 Commits: 4fdd9ea 后遇到错误

### ISSUE THREAD

**Issue by crysehillmes** [breakwa11/shadowsocks#100]
刚刚更新到`4fdd9ea` 遇到错误：
```
2016-07-18 01:28:12 ERROR    db_transfer.py:232 Traceback (most recent call last):
  File "/opt/shadowsocks/db_transfer.py", line 226, in thread_db
    db_instance.push_db_all_user()
  File "/opt/shadowsocks/db_transfer.py", line 87, in push_db_all_user
    for id in update_transfer.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```
回退到 `d8dda50` 后恢复正常。

**Comment by Aar0nJaw** [comment]
一样的问题

**Comment by breakwa11** [comment]
更正了。。。

**Comment by crysehillmes** [comment]
@breakwa11 刚刚试了下可以了，辛苦啦~
