### ISSUE TITLE
启动时报错socket Errno:10047

### ISSUE THREAD

**Issue by w123rq** [breakwa11/shadowsocks#112]
Python版本2.7  windows2003
C:\dd\shadowsocks-master\shadowsocks>python server.py -h
Traceback (most recent call last):
  File "server.py", line 32, in <module>
    from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, \
  File "C:\dd\shadowsocks-master\shadowsocks\../shadowsocks\asyncdns.py", line 9
3, in <module>
    IPV6_CONNECTION_SUPPORT = detect_ipv6_supprot()
  File "C:\dd\shadowsocks-master\shadowsocks\../shadowsocks\asyncdns.py", line 8
3, in detect_ipv6_supprot
    s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
  File "C:\Python27\lib\socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 10047]

**Comment by w123rq** [comment]
已解决，使用python3.x版本即可，但3.5有问题
