### ISSUE TITLE
both auth_aes128_md5/sha1 not work

### ISSUE THREAD

**Issue by hweidz** [breakwa11/shadowsocks#124]
server: 2.9.5
client:3.9.5

2016-10-12 21:17:20 ERROR    tcprelay.py:876 can not parse header when handling connection from 192.168.1.100:59451
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shadowsocks/tcprelay.py", line 493, in _handle_stage_addr
    data = self._handel_protocol_error(self._client_address, ogn_data)
  File "/usr/lib/python2.7/site-packages/shadowsocks/tcprelay.py", line 392, in _handel_protocol_error
    raise Exception('can not parse header')
Exception: can not parse header
2016-10-12 21:17:21 ERROR    tcprelay.py:876 can not parse header when handling connection from 192.168.1.100:59452
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shadowsocks/tcprelay.py", line 493, in _handle_stage_addr
    data = self._handel_protocol_error(self._client_address, ogn_data)
  File "/usr/lib/python2.7/site-packages/shadowsocks/tcprelay.py", line 392, in _handel_protocol_error
    raise Exception('can not parse header')
Exception: can not parse header
2016-10-12 21:17:25 ERROR    tcprelay.py:876 can not parse header when handling connection from 192.168.1.100:59454
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shadowsocks/tcprelay.py", line 493, in _handle_stage_addr
    data = self._handel_protocol_error(self._client_address, ogn_data)
  File "/usr/lib/python2.7/site-packages/shadowsocks/tcprelay.py", line 392, in _handel_protocol_error
    raise Exception('can not parse header')
Exception: can not parse header
2016-10-12 21:17:25 ERROR    tcprelay.py:876 can not parse header when handling connection from 192.168.1.100:59455
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shadowsocks/tcprelay.py", line 493, in _handle_stage_addr
    data = self._handel_protocol_error(self._client_address, ogn_data)
  File "/usr/lib/python2.7/site-packages/shadowsocks/tcprelay.py", line 392, in _handel_protocol_error
    raise Exception('can not parse header')
Exception: can not parse header

**Comment by breakwa11** [comment]
@hweidz you are running ss, not ssr
