### ISSUE TITLE
OpenSSL 1.1.0c  ubuntu16.04 Python 2.7.12出错

### ISSUE THREAD

**Issue by tianrking** [breakwa11/shadowsocks#136]
loaded collections.OrderedDict
IPv6 support
INFO: loading config from justforfun/ssr.json
2016-11-22 14:01:28 INFO     util.py:85 loading libcrypto from libcrypto.so.1.1
Traceback (most recent call last):
  File "shadowsocks/shadowsocks/server.py", line 215, in <module>
    main()
  File "shadowsocks/shadowsocks/server.py", line 38, in main
    config = shell.get_config(False)
  File "/home/shadowsocks/shadowsocks/../shadowsocks/shell.py", line 311, in get_config
    check_config(config, is_local)
  File "/home/shadowsocks/shadowsocks/../shadowsocks/shell.py", line 147, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/home/shadowsocks/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/home/shadowsocks/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/home/shadowsocks/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/home/shadowsocks/shadowsocks/../shadowsocks/crypto/rc4_md5.py", line 33, in create_cipher
    return openssl.OpenSSLCrypto(b'rc4', rc4_key, b'', op)
  File "/home/shadowsocks/shadowsocks/../shadowsocks/crypto/openssl.py", line 88, in __init__
    load_openssl()
  File "/home/shadowsocks/shadowsocks/../shadowsocks/crypto/openssl.py", line 52, in load_openssl
    libcrypto.EVP_CIPHER_CTX_cleanup.argtypes = (c_void_p,)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libcrypto.so.1.1: undefined symbol: EVP_CIPHER_CTX_cleanup

**Comment by breakwa11** [comment]
@tianrking 你换成aes加密试试

**Comment by tianrking** [comment]
@breakwa11 
欧耶 找到原因了 openssl 弃用了 EVP_CIPHER_CTX_cleanup变成reset 网上这么说的 然后我就试着改了下 crypto 可以运行了
52行: libcrypto.EVP_CIPHER_CTX_cleanup.argtypes = (c_void_p,)
修改成
libcrypto.EVP_CIPHER_CTX_reset.argtypes = (c_void_p,)
123行: 
libcrypto.EVP_CIPHER_CTX_cleanup.argtypes = (c_void_p,)
修改成
libcrypto.EVP_CIPHER_CTX_reset(self._ctx)
(*^__^*)

**Comment by breakwa11** [comment]
@tianrking 好的，我改一下

**Comment by breakwa11** [comment]
测试一下最新代码试试

**Comment by tianrking** [comment]
😀 对劲 就是这样  可以使用了  辛苦了
