### ISSUE TITLE
服务端自动关闭

### ISSUE THREAD

**Issue by zhioa** [breakwa11/shadowsocks#137]
![20161124170050](https://cloud.githubusercontent.com/assets/22550365/20592383/0f7ae01a-b268-11e6-94e2-79d1b2bb0853.png)
![20161124170059](https://cloud.githubusercontent.com/assets/22550365/20592384/0f8c1a6a-b268-11e6-8a39-60459fc07b2c.png)

查看了一下log
请问这是什么情况?

**Comment by zhioa** [comment]
2016-11-24 12:28:29 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 332, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 252, in __init__
    self.autocommit(False)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 283, in autocommit
    self.errorhandler(None, exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

2016-11-23 12:25:55 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 208, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 66, in push_db_all_user
    update_transfer = self.update_all_user(dt_transfer) #返回有更新的表
  File "/root/shadowsocks/db_transfer.py", line 302, in update_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 62, in __init__
    self.__recv_packet()
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 81, in __recv_packet
    packet_header = self.__recv_from_socket(4)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 74, in __recv_from_socket
    raise OperationalError(2013, "Lost connection to MySQL server during query")
OperationalError: (2013, 'Lost connection to MySQL server during query')

**Comment by breakwa11** [comment]
服务端版本呢？请提交issue时，务必包含具体版本号，及配置

**Comment by zhioa** [comment]
@breakwa11  2.9.6及2.9.7 都出现这个问题 求解

**Comment by breakwa11** [comment]
但这个错误应该并不影响使用，这个和连接被RST或超时断开是一样的

**Comment by zhioa** [comment]
是服务端直接挂了 连接不了  重启服务端也出现这个问题 要重启几次服务端才正常
1天挂1次 不知道是啥问题 @breakwa11

**Comment by breakwa11** [comment]
你的mysql服务器和节点间的连接如何？速度快吗？丢包吗？如果是挂了，那和这个log没有任何关系，请提供其它的log，以及你服务器本身的配置

**Comment by zhioa** [comment]
2016-11-24 12:32:03 INFO     udprelay.py:1375 closed UDP port 10483
2016-11-24 12:32:03 INFO     udprelay.py:1375 closed UDP port 10396
2016-11-24 12:32:03 INFO     udprelay.py:1375 closed UDP port 10397
2016-11-24 12:32:03 INFO     udprelay.py:1375 closed UDP port 10484
2016-11-24 12:32:03 INFO     udprelay.py:1375 closed UDP port 10485
2016-11-24 12:32:03 INFO     udprelay.py:1375 closed UDP port 10486
2016-11-24 12:32:08 INFO     tcprelay.py:1107 closed TCP port 10028
2016-11-24 12:32:08 INFO     tcprelay.py:1107 closed TCP port 10064
2016-11-24 12:32:08 INFO     tcprelay.py:1107 closed TCP port 10065
2016-11-24 12:32:08 INFO     tcprelay.py:1107 closed TCP port 10066
2016-11-24 12:32:08 INFO     tcprelay.py:1107 closed TCP port 10067
2016-11-24 12:32:08 INFO     tcprelay.py:1107 closed TCP port 10071
2016-11-24 12:32:08 INFO     tcprelay.py:1107 closed TCP port 10074
2016-11-24 12:32:08 INFO     tcprelay.py:1107 closed TCP port 10075

对了 log还现了这个

mysql和网站都放在digitalocean San Francisco 同一个vps上
512MB的
阿里香港节点服务端连接的

**Comment by breakwa11** [comment]
@zhioa 这个log也不是关键，在这前面呢？

**Comment by zhioa** [comment]
2016-11-24 11:48:40 ERROR    tcprelay.py:844 [Errno 110] Connection timed out
2016-11-24 11:48:40 ERROR    tcprelay.py:846 when connect to xxxxxxx
2016-11-24 11:48:42 ERROR    tcprelay.py:844 [Errno 111] Connection refused
2016-11-24 11:48:42 ERROR    tcprelay.py:846 when connect to xxxxxxx
2016-11-24 11:48:44 ERROR    tcprelay.py:837 [Errno 104] Connection reset by peer
2016-11-24 11:48:44 ERROR    tcprelay.py:838 exception from xxxxxxxx
2016-11-24 11:48:47 ERROR    tcprelay.py:844 [Errno 111] Connection refused
2016-11-24 11:48:47 ERROR    tcprelay.py:846 when connect to xxxxxx
2016-11-24 11:48:52 ERROR    tcprelay.py:844 [Errno 111] Connection refused
2016-11-24 11:48:52 ERROR    tcprelay.py:846 when connect to xxxxxxxx
2016-11-24 11:48:53 ERROR    tcprelay.py:844 [Errno 110] Connection timed out
2016-11-24 11:48:53 ERROR    tcprelay.py:846 when connect to xxxxxxxxxx
2016-11-24 11:48:58 ERROR    db_transfer.py:337 (<class 'socket.timeout'>, timeout('timed out',))
2016-11-24 11:48:58 WARNING  db_transfer.py:342 no user in db

2016-11-24 11:48:58 INFO     server_pool.py:200 stopped server at [::]:10485 already stop
2016-11-24 11:48:58 INFO     db_transfer.py:149 db stop server at port [10486] reason: port not exist
2016-11-24 11:48:58 INFO     server_pool.py:186 stopped server at 0.0.0.0:10486
2016-11-24 11:48:58 INFO     server_pool.py:200 stopped server at [::]:10486 already stop
2016-11-24 11:48:58 INFO     db_transfer.py:149 db stop server at port [10285] reason: port not exist
2016-11-24 11:48:58 INFO     server_pool.py:186 stopped server at 0.0.0.0:10285
2016-11-24 11:48:58 INFO     server_pool.py:200 stopped server at [::]:10285 already stop


2016-11-24 11:53:38 ERROR    db_transfer.py:216 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 209, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 332, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 252, in __init__
    self.autocommit(False)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 283, in autocommit
    self.errorhandler(None, exc, value)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

INFO: loading config from /root/shadowsocks/user-config.json
2016-11-24 11:54:28 INFO     util.py:85 loading libsodium from libsodium.so.18
2016-11-24 11:54:28 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-11-24 11:54:28 INFO     shell.py:80 ShadowsocksR 2.9.7 2016-11-22
2016-11-24 11:54:28 INFO     db_transfer.py:202 current process RLIMIT_NOFILE resource: soft 512000 hard 1024000
2016-11-24 11:55:41 ERROR    db_transfer.py:337 (<class 'socket.timeout'>, timeout('timed out',))
2016-11-24 11:55:41 WARNING  db_transfer.py:342 no user in db
INFO: loading config from /root/shadowsocks/user-config.json
2016-11-24 11:56:50 INFO     util.py:85 loading libsodium from libsodium.so.18
2016-11-24 11:56:50 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-11-24 11:56:50 INFO     shell.py:80 ShadowsocksR 2.9.7 2016-11-22
2016-11-24 11:56:50 INFO     db_transfer.py:202 current process RLIMIT_NOFILE resource: soft 512000  hard 512000 
INFO: loading config from /root/shadowsocks/user-config.json
2016-11-24 11:58:48 INFO     util.py:85 loading libsodium from libsodium.so.18
2016-11-24 11:58:48 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2016-11-24 11:58:48 INFO     shell.py:80 ShadowsocksR 2.9.7 2016-11-22
2016-11-24 11:58:48 INFO     db_transfer.py:202 current process RLIMIT_NOFILE resource: soft 512000 hard 512000 
2016-11-24 12:00:34 INFO     db_transfer.py:171 db start server at port [10120] pass [xxxxxxx] protocol [auth_sha1_v4_compatible] method [chacha20] obfs [tls1.2_ticket_auth_compatible]
2016-11-24 12:00:34 INFO     server_pool.py:127 starting server at [::]:10120
2016-11-24 12:00:34 WARNING  server_pool.py:140 IPV6 [Errno 97] Address family not supported by protocol

还有这些 你看看是不是?

**Comment by breakwa11** [comment]
你更新一下再试试

**Comment by zhioa** [comment]
好的 等一下更新看看 测试2天 再回来反馈

**Comment by zhioa** [comment]
@breakwa11用了2天 没有出现挂服务端 log也没看见相关错误 应该是解决了 感谢作者更新
不过话说log 看见好多Connection refused Connection timed out 错误 不过也不影响使用
这些错误是不是不用管也可以?

**Comment by breakwa11** [comment]
@zhioa 是的，不用管

**Comment by zhioa** [comment]
好的 明白 再次感谢作者的帮忙
