### ISSUE TITLE
不明的程序崩潰

### ISSUE THREAD

**Issue by akw28888** [breakwa11/shadowsocks#14]
```
Unhandled exception in thread started by <function _loop at 0x233a1b8>
Traceback (most recent call last):
  File "/root/shadowsocks/server_pool.py", line 69, in _loop
  File "/root/shadowsocks/shadowsocks/eventloop.py", line 216, in run
  File "/root/shadowsocks/shadowsocks/tcprelay.py", line 830, in handle_event
  File "/root/shadowsocks/shadowsocks/tcprelay.py", line 116, in __init__
  File "/root/shadowsocks/shadowsocks/encrypt.py", line 85, in __init__
  File "/root/shadowsocks/shadowsocks/encrypt.py", line 37, in random_string
NotImplementedError: /dev/urandom (or equivalent) not found
```

最新commit的manyuser分支 突然就這樣 程序crash了？

**Comment by falseen** [comment]
/dev/urandom   先看下有没有这个文件。

**Comment by breakwa11** [comment]
在这个错误之前或之后有没有too many open files?

**Comment by breakwa11** [comment]
有没有可能是没有安装m2crypto，试试安装一下看看

**Comment by Arnaud-Github** [comment]
2015-09-24 07:19:45 ERROR    [Errno 24] Too many open files
Unhandled exception in thread started by <function _loop at 0x7f2a215d5cf8>
Traceback (most recent call last):
  File "/root/pip-7.0.3/shadowsocks/server_pool.py", line 69, in _loop
  File "/root/pip-7.0.3/shadowsocks/shadowsocks/eventloop.py", line 216, in run
  File "/root/pip-7.0.3/shadowsocks/shadowsocks/tcprelay.py", line 830, in handle_event
  File "/root/pip-7.0.3/shadowsocks/shadowsocks/tcprelay.py", line 116, in __init__
  File "/root/pip-7.0.3/shadowsocks/shadowsocks/encrypt.py", line 85, in __init__
  File "/root/pip-7.0.3/shadowsocks/shadowsocks/encrypt.py", line 37, in random_string
NotImplementedError: /dev/urandom not found

**Comment by Arnaud-Github** [comment]
@breakwa11 我也有相同情况

**Comment by falseen** [comment]
@Arnaud-Github 安装之后要做相关的优化。
可参考以下方式进行优化：

https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks

https://github.com/shadowsocks/shadowsocks/wiki/Shadowsocks-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

http://wuchong.me/blog/2015/02/02/shadowsocks-install-and-optimize/

**Comment by Arnaud-Github** [comment]
@falseen 这些我都是改过的

**Comment by liuchao0130** [comment]
我每次都遇到这个问题，实在用不了，暂时回到SS

**Comment by falseen** [comment]
@liuchao0130  有没有完整的日志？
