### ISSUE TITLE
windows下的兼容性问题

### ISSUE THREAD

**Issue by falseen** [breakwa11/shadowsocks#22]
最近发现的兼容性问题有点多，感觉有必要记录一下，这个issue专门用来记录windows下的兼容问题。

**Comment by falseen** [comment]
python版本：2.7（64位）
系统 ：64位 win7

运行多用户版本时如果数据库有变动会出现以下错误：
```python
2015-10-16 00:16:02 INFO     db stop server at port [7656] reason: obfs changed
2015-10-16 00:16:02 INFO     stopped server at 0.0.0.0:7656
2015-10-16 00:16:02 INFO     stopped server at :::7656
Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "E:\python\shadowsocks\server_pool.py", line 44, in run
    ServerPool._loop(*self.params)
  File "E:\python\shadowsocks\server_pool.py", line 77, in _loop
    loop.run()
  File "E:\python\shadowsocks\shadowsocks\eventloop.py", line 197, in run
    events = self.poll(TIMEOUT_PRECISION)
  File "E:\python\shadowsocks\shadowsocks\eventloop.py", line 167, in poll
    return [(self._fdmap[fd][0], fd, event) for fd, event in events]
KeyError: 520L

```
之后程序进入假死状态。

**Comment by breakwa11** [comment]
已经修好了吧？
