### ISSUE TITLE
在阿里云ECS上运行出错

### ISSUE THREAD

**Issue by ZeroClover** [breakwa11/shadowsocks#32]
CentOS 6.5 x64，已经安装了所有依赖
提示：
Traceback (most recent call last):
  File "server.py", line 27, in <module>
    import server_pool
  File "/root/shadowsocks/server_pool.py", line 31, in <module>
    from shadowsocks import asyncdns
  File "/root/shadowsocks/shadowsocks/asyncdns.py", line 93, in <module>
    IPV6_CONNECTION_SUPPORT = detect_ipv6_supprot()
  File "/root/shadowsocks/shadowsocks/asyncdns.py", line 83, in detect_ipv6_supprot
    s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
  File "/usr/lib64/python2.6/socket.py", line 184, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 97] Address family not supported by protocol

**Comment by breakwa11** [comment]
更新一下试试

**Comment by ZeroClover** [comment]
刚刚git clone下来的，反正rm再clone了很多次都是这样，用那个mengskysama的反而没出问题。。。

**Comment by breakwa11** [comment]
我意思是3分钟前我改了一下

**Comment by ZeroClover** [comment]
2015-11-27 15:56:18 WARNING  IPV6 [Errno 97] Address family not supported by protocol 
2015-11-27 15:56:18 INFO     starting server at 0.0.0.0:20148
2015-11-27 15:56:33 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 159, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 88, in pull_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 138, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1226, u"User 'vedbs_368' has exceeded the 'max_user_connections' resource (current value: 10)")

2015-11-27 15:56:48 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 159, in thread_db
    rows = DbTransfer.get_instance().pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 88, in pull_db_all_user
    passwd=Config.MYSQL_PASS, db=Config.MYSQL_DB, charset='utf8')
  File "/usr/lib/python2.6/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/lib/python2.6/site-packages/cymysql/packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 138, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1226, u"User 'vedbs_368' has exceeded the 'max_user_connections' resource (current value: 10)")

**Comment by breakwa11** [comment]
数据库的连接数限制你自己修改吧，看你的log就是问题已经解决了
