### ISSUE TITLE
shadowsocks server端啟動時, py提示錯誤

### ISSUE THREAD

**Issue by akw28888** [breakwa11/shadowsocks#4]
<root@ssnode:~/shadowsocks# python server.py
INFO: loading config from config.json
2015-08-05 14:33:28 INFO     loading libcrypto from libcrypto.so.1.0.0
Shadowsocks
Unhandled exception in thread started by <function _loop at 0x9763e2c>
Traceback (most recent call last):
  File "/root/shadowsocks/server_pool.py", line 67, in _loop
    mgr.add_to_loop(loop)
  File "/root/shadowsocks/asyncmgr.py", line 58, in add_to_loop
    loop.add(self._sock, eventloop.POLL_IN)
TypeError: add() takes exactly 4 arguments (3 given)
2015-08-05 14:33:29 INFO     db start server at port [XXXX] pass [xxxx]>
(後略)
os: debian 7 x86
該裝的東西應該都是裝好的了 不知道error在哪?

**Comment by breakwa11** [comment]
再从git更新一下服务端代码，多用户有部分代码没更新完全导致的
