### ISSUE TITLE
运行ssserver -h报错

### ISSUE THREAD

**Issue by testcaoy7** [breakwa11/shadowsocks#40]
版本：2.6.12
错误信息：
Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.6.12', 'console_scripts', 'ssserver')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks-2.6.12-py2.7.egg/shadowsocks/server.py", line 31, in <module>
    from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, \
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks-2.6.12-py2.7.egg/shadowsocks/tcprelay.py", line 30, in <module>
    from shadowsocks import encrypt, obfs, eventloop, shell, common
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks-2.6.12-py2.7.egg/shadowsocks/obfs.py", line 26, in <module>
    from shadowsocks.obfsplugin import plain, http_simple, obfs_tls, verify, auth
ImportError: No module named obfsplugin

刚刚到python-pip里翻了一下，并没有找到obfsplugin，请问这个问题如何解决？

**Comment by breakwa11** [comment]
你怎么安装的？

**Comment by breakwa11** [comment]
目前用python-pip的方式安装还不行，脚本没有配置好，你试试按wiki的方式来配置你的服务端

**Comment by testcaoy7** [comment]
首先 git clone https://github.com/breakwa11/shadowsocks.git
然后 cd shadowsocks
最后 python setup.py install

安装完成后却无法运行，报错No module named obfsplugin

应该是git版本的问题，release我还没有试

**Comment by testcaoy7** [comment]
对了，我是安装在docker版的ubuntu容器里的，是不是系统里缺东西？现在想来也有可能。。。

**Comment by breakwa11** [comment]
你的分支拿错了，要用manyuser分支，主分支很多东西不是新的

**Comment by testcaoy7** [comment]
哦，原来如此
