### ISSUE TITLE
使用ssr版manyuser其他主机来中转服务很快就会挂掉

### ISSUE THREAD

**Issue by geniusxiaoxiao** [breakwa11/shadowsocks#59]
举例A主机安装manyuser，SS可正常使用。
B主机纯转发端口流量，不安装其他任何服务只转发tcp/udp流量至A主机，也可以正常使用。
但是一旦用户多了连接数大了A主机的SS服务就会挂掉...导致A/B都无法使用
可是源版也就是原来未修改版的manyuser没有这个问题。
希望能够解决！或能够提供我一下其他的解决方案！感谢！

**Comment by breakwa11** [comment]
那你测试过直接连接A的话，用户多了会挂掉吗？你的A主机硬件配置是什么，SS配置是什么，系统的连接数限制配置呢？

**Comment by geniusxiaoxiao** [comment]
直接连接A 用户再多也不会有任何问题。奇怪的是只有当B中转A后会产生这个问题。
我是在B主机上用iptables是实现多端口段来转发的。单个端口或者单独转发几个没有问题，但如果多了比如50000:53000就会有这样的问题了。不过也不是马上挂掉，正常后过了1小时或3,4个小时后A才会挂掉。
A主机用的是Linode的2048。包括测试Vultr,Sakura,SoftLayer等主机都情况相同。但如果不开manyuser不开udp也就是使用旧版本的manyuser却不存在这个问题

**Comment by Mujj** [comment]
应该是链表挂了，定时重启下iptables试试吧。

**Comment by geniusxiaoxiao** [comment]
无解么....没人发现有这样的问题？

**Comment by geniusxiaoxiao** [comment]
已根据log日志解决

**Comment by geniusxiaoxiao** [comment]
彻底杀掉运行正常，但是过几小时就又会链接不上，
总之，只要SS服务器被大面积中转就会导致挂掉
但是进程里看到的还是运行着，也就是进程活着但其实已经链接不上了。可源版本的manyuser却没有这个问题

**Comment by breakwa11** [comment]
你试试把Config.py里的MANAGE_PORT = 23333改为MANAGE_PORT = 65535试试

**Comment by geniusxiaoxiao** [comment]
还是不行... T_T

**Comment by geniusxiaoxiao** [comment]
报错信息：
Exception in thread Thread-2:
Traceback (most recent call last): 
File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
File "/root/shadowsocks/server_pool.py", line 44, in run
File "/root/shadowsocks/server_pool.py", line 83, in _loop
File "/root/shadowsocks/shadowsocks/eventloop.py", line 216, in run                                      File "/root/shadowsocks/shadowsocks/tcprelay.py", line 966, in handle_event
File "/root/shadowsocks/shadowsocks/tcprelay.py", line 112, in __init__
File "/root/shadowsocks/shadowsocks/encrypt.py", line 87, in __init__
File "/root/shadowsocks/shadowsocks/encrypt.py", line 37, in random_string
NotImplementedError: /dev/urandom (or equivalent) not found

**Comment by breakwa11** [comment]
是不是UDP也中转了，我不确认中转UDP会发生什么，从错误信息来看，是系统资源用光了

**Comment by geniusxiaoxiao** [comment]
单独中转tcp也会有这样的问题....我用Linode4096方案测试也会这样....也就是4G内存4核心处理器
但是真的是以前老的manyuser不会有这样的问题啊 T_T
如果没办法的话...也就只能用老版的manyuser了....
但是我目前测试下来是CentOS很快会报错这样的问题，Debian至少还能坚持一个晚上多。比如半夜0点开好明天下午大概就会报错....CentOS基本一晚上就肯定会出现问题。

**Comment by breakwa11** [comment]
似乎修好了
