### ISSUE TITLE
提交个bug，shadowsocks多用户版，修改密码后无法使用

### ISSUE THREAD

**Issue by niuniu123** [breakwa11/shadowsocks#6]
提交个bug，shadowsocks多用户版，修改任何一个端口的密码，将导致所有端口（包括修改的端口）无法使用，必须的重启shadowsocks服务器才行。
这个bug对于多用户版应该算是致命的了，一个用户修改密码，呵呵，所有用户都不能用了。
以前老版本也有这个问题，为啥没用户发现呢!

[root@***~]# cd shadowsocks
[root@*** shadowsocks]# ./tail.sh
Traceback (most recent call last):
  File "/root/shadowsocks/server_pool.py", line 69, in _loop
    loop.run()
  File "/root/shadowsocks/shadowsocks/eventloop.py", line 210, in run
    handler.handle_event(sock, fd, event)
AttributeError: 'ServerMgr' object has no attribute 'handle_event'
2015-08-09 17:02:03 INFO     db stop server at port [10000] reason: password cha
nged
2015-08-09 17:02:03 INFO     del server at 10000
2015-08-09 17:02:19 INFO     db stop server at port [10000] reason: password cha
nged
2015-08-09 17:02:19 INFO     del server at 10000
2015-08-09 17:02:35 INFO     db stop server at port [10000] reason: password cha
nged
2015-08-09 17:02:35 INFO     del server at 10000
2015-08-09 17:02:51 INFO     db stop server at port [10000] reason: password cha
nged
2015-08-09 17:02:51 INFO     del server at 10000
2015-08-09 17:03:07 INFO     db stop server at port [10000] reason: password cha
nged

**Comment by breakwa11** [comment]
噢，有一个非常白痴的错误没改，马上搞

**Comment by breakwa11** [comment]
应该正确了，测试一下

**Comment by asdqwe876** [comment]
错误依然存在，还是那两个文件

**Comment by breakwa11** [comment]
好了，修好了

**Comment by niuniu123** [comment]
升级到了最新版，并重启了shadowsocks服务器
问题如下：修改密码后，原密码依旧可用(约过了几十秒后，原密码不可用)，新修改的密码也不能用（未修改过密码的端口也无法使用），提示如下错误：
[root@***** shadowsocks]# ./tail.sh
2015-08-11 18:36:04 ERROR    can not parse header when handling connection from
::ffff:58.20.28.***:34509
2015-08-11 18:36:07 WARNING  unsupported addrtype 39, maybe wrong password or en
cryption method
2015-08-11 18:36:07 ERROR    can not parse header when handling connection from
::ffff:58.20.28.***:34821
2015-08-11 18:36:08 WARNING  unsupported addrtype 171, maybe wrong password or e
ncryption method
2015-08-11 18:36:08 ERROR    can not parse header when handling connection from
::ffff:58.20.28.221:34609
2015-08-11 18:36:08 WARNING  unsupported addrtype 73, maybe wrong password or en
cryption method
2015-08-11 18:36:08 ERROR    can not parse header when handling connection from
::ffff:58.20.28.***:36366
2015-08-11 18:36:08 WARNING  unsupported addrtype 69, maybe wrong password or en
cryption method
2015-08-11 18:36:08 ERROR    can not parse header when handling connection from
::ffff:58.20.28.***:33806
2015-08-11 18:36:20 INFO     stopping

其中58.20.28.***是我的本地ip

依旧需重启shadowsocks服务器后，才恢复正常。

**Comment by breakwa11** [comment]
找到根本原因了，去除了异步操作，同时让改密码的生效时间减半，保证15秒内一定生效
