### ISSUE TITLE
流量统计失效AttributeError: 'module' object has no attribute 'MYSQL_TRANSFER_MUL'

### ISSUE THREAD

**Issue by PaytonShaw** [breakwa11/shadowsocks#69]
2016-03-08 22:08:27 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 174, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 50, in push_db_all_user
    dt_transfer[id] = [int(curr_transfer[id][0] * Config.MYSQL_TRANSFER_MUL),
AttributeError: 'module' object has no attribute 'MYSQL_TRANSFER_MUL'

**Comment by iansiu** [comment]
我也是这个问题，解决了吗？

**Comment by breakwa11** [comment]
这问题是你自己的代码没有更新到最新，Config.py文件不是最新
