### ISSUE TITLE
配合 ss-panel v3 之后产生的一点问题

### ISSUE THREAD

**Issue by agentmario** [breakwa11/shadowsocks#81]
用户达到 10 之后似乎就不能自动增加新用户了，必须手动重开后端。
现在启动的时候还会出现这样的 log
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "server.py", line 40, in run
    db_transfer.DbTransfer.thread_db()
  File "/root/shadowsocks-manyuser/db_transfer.py", line 183, in thread_db
    if DbTransfer.get_instance().event.wait(Config.MYSQL_UPDATE_TIME):
AttributeError: 'module' object has no attribute 'MYSQL_UPDATE_TIME'
```

**Comment by breakwa11** [comment]
你的配置文件Config.py没有成功更新
